
PREFIX geo: <http://purl.obolibrary.org/obo/geo.owl#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX ro: <http://www.obofoundry.org/ro/ro.owl#>
PREFIX obo: <http://purl.obolibrary.org/obo/>
PREFIX dc: <http://purl.org/dc/elements/1.1/>


DELETE {
    GRAPH <http://www.pitt.edu/obc/ide/article-instances> {
        <##MODEL##> dc:title ?title .
        <##MODEL##> <http://purl.obolibrary.org/obo/ERO_0000480> ?linkout .
        <##MODEL##> <http://www.pitt.edu/obc/IDE_source_organization> ?sourceOrganization .
        <##MODEL##> <http://purl.org/dc/elements/1.1/date> ?date . 
        <##MODEL##> obo:IAO_0000136 ?about .
        <##MODEL##> rdf:type ?types .
        <##MODEL##> <http://www.pitt.edu/obc/IDE_version> ?version .
        <##MODEL##> <http://www.pitt.edu/obc/IDE_0000000040> ?doi .
        <##MODEL##> <http://purl.obolibrary.org/obo/APOLLO_SV_00000325> ?dateIndexed .
    }
} INSERT {
    GRAPH <http://www.pitt.edu/obc/ide/article-instances> { 
        <##MODEL##> dc:title "##TITLE##" .
        <##MODEL##> <http://purl.obolibrary.org/obo/ERO_0000480> "##LINKOUT##" .
        <##MODEL##> <http://www.pitt.edu/obc/IDE_source_organization> "##SOURCE##" .
        <##MODEL##> <http://purl.org/dc/elements/1.1/date> "##DATE##" . 
        <##MODEL##> rdf:type <##TYPE##> .
        <##MODEL##> <http://www.pitt.edu/obc/IDE_version> "##VERSION##" .
        <##MODEL##> <http://www.pitt.edu/obc/IDE_0000000040> "##DOI##" .
        <##MODEL##> <http://purl.obolibrary.org/obo/APOLLO_SV_00000325> "##DATEINDEXED##" .
        ##ABOUTS##
    } 
} 
USING <http://www.pitt.edu/obc/ide/apollo-sv>
USING <http://www.pitt.edu/obc/ide/classes-and-indexing-instances>
USING <http://www.pitt.edu/obc/ide/article-instances>

WHERE {
    OPTIONAL { <##MODEL##> dc:title ?title } .
    OPTIONAL { <##MODEL##> <http://purl.obolibrary.org/obo/ERO_0000480> ?linkout } .
    OPTIONAL { <##MODEL##> <http://www.pitt.edu/obc/IDE_source_organization> ?sourceOrganization } .
    OPTIONAL { <##MODEL##> <http://purl.org/dc/elements/1.1/date> ?date } . 
    OPTIONAL { <##MODEL##> obo:IAO_0000136 ?about } .
    OPTIONAL { <##MODEL##> rdf:type ?types } .
    OPTIONAL { <##MODEL##> <http://www.pitt.edu/obc/IDE_version> ?version } .
    OPTIONAL { <##MODEL##> <http://www.pitt.edu/obc/IDE_0000000040> ?doi } .
    OPTIONAL { <##MODEL##> <http://purl.obolibrary.org/obo/APOLLO_SV_00000325> ?dateIndexed } .
}