PREFIX geo: <http://purl.obolibrary.org/obo/geo.owl#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX ro: <http://www.obofoundry.org/ro/ro.owl#>
PREFIX obo: <http://purl.obolibrary.org/obo/>
PREFIX dc: <http://purl.org/dc/elements/1.1/>

SELECT DISTINCT ?grant ?title ?awardee ?foa ?agency ?pi ?grantid ?grantidlabel ?start ?end ?grantLinkout ?pub ?pubName ?linkout ?date ?sourceOrganization ?authors ?journal ?typeLabel ?dateIndexed ?pmid
    (group_concat(DISTINCT ?aboutLabel ; separator = " :: ") as ?abouts)
FROM <http://www.pitt.edu/obc/ide/apollo-sv>
FROM <http://www.pitt.edu/obc/ide/classes-and-indexing-instances>
FROM <http://www.pitt.edu/obc/ide/article-instances>
WHERE {

    ?grant rdf:type ?type .
    ?type rdfs:subClassOf* obo:OBI_0001636 .
    ?type rdfs:label ?typeLabel .
    ?grant dc:title ?title .
    ?grant obo:IDE_0000000174 ?awardee .
    ?grant obo:IDE_0000000172 ?foa .
    ?grant obo:IDE_0000000173 ?agency .
    ?grant obo:IDE_0000000171 ?pi .
    ?grant obo:IDE_0000000169 ?start .
    ?grant obo:IDE_0000000170 ?end .
    ?grantid obo:IAO_0000219 ?grant .
    ?grantid rdfs:label ?grantidlabel .

    ?grant obo:IAO_0000136 ?about .
    ?about rdfs:label ?aboutLabel .

    #used for string interpolation to filter based on search terms


    OPTIONAL {  ?grant <http://purl.obolibrary.org/obo/APOLLO_SV_00000325> ?dateIndexed } .
    OPTIONAL {  ?grant <http://purl.obolibrary.org/obo/ERO_0000480> ?grantLinkout } .
    OPTIONAL {  ?grant obo:BFO_0000051 ?os .
                ?pp obo:OBI_0000417 ?os  .
                ?pub obo:IAO_0000136 ?pp } .

    OPTIONAL {  ?grant obo:BFO_0000051 ?os .
                ?pp obo:OBI_0000417 ?os  .
                ?pub obo:IAO_0000136 ?pp .
                ?pub dc:title ?pubName } .

    OPTIONAL {  ?grant obo:BFO_0000051 ?os .
                ?pp obo:OBI_0000417 ?os  .
                ?pub obo:IAO_0000136 ?pp .
                ?pub <http://purl.obolibrary.org/obo/OBI_0001617> ?pmid } .

    OPTIONAL {  ?grant obo:BFO_0000051 ?os .
                ?pp obo:OBI_0000417 ?os  .
                ?pub obo:IAO_0000136 ?pp .
                ?pub dc:title ?title } .

    OPTIONAL { ?grant obo:BFO_0000051 ?os .
                ?pp obo:OBI_0000417 ?os  .
                ?pub obo:IAO_0000136 ?pp .
                ?pub <http://purl.obolibrary.org/obo/ERO_0000480> ?linkout } .

    OPTIONAL {  ?grant obo:BFO_0000051 ?os .
                ?pp obo:OBI_0000417 ?os  .
                ?pub obo:IAO_0000136 ?pp .
                ?pub <http://purl.org/dc/elements/1.1/date> ?date } .

    OPTIONAL {  ?grant obo:BFO_0000051 ?os .
                ?pp obo:OBI_0000417 ?os  .
                ?pub obo:IAO_0000136 ?pp .
                ?pub <http://www.pitt.edu/obc/IDE_source_organization> ?sourceOrganization } .

    OPTIONAL {  ?grant obo:BFO_0000051 ?os .
                ?pp obo:OBI_0000417 ?os  .
                ?pub obo:IAO_0000136 ?pp .
                ?pub <http://www.pitt.edu/obc/AUTHORS_1> ?authors } .

    OPTIONAL {
                ?grant obo:BFO_0000051 ?os .
                ?pp obo:OBI_0000417 ?os  .
                ?pub obo:IAO_0000136 ?pp .
                ?pub <http://purl.obolibrary.org/obo/BFO_0000137> ?journalUri .
        ?journalUri dc:title ?journal .
    } .

    #used for string interpolation to filter based on search terms
    ##ABOUT##

} GROUP BY ?grant ?title ?awardee ?foa ?agency ?pi ?grantid ?grantidlabel ?start ?end ?grantLinkout ?pub ?pubName ?linkout ?date ?sourceOrganization ?authors ?journal ?typeLabel ?dateIndexed ?pmid