PREFIX geo: <http://purl.obolibrary.org/obo/geo.owl#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX ro: <http://www.obofoundry.org/ro/ro.owl#>
PREFIX obo: <http://purl.obolibrary.org/obo/>
PREFIX dc: <http://purl.org/dc/elements/1.1/>
 
 
DELETE {
    GRAPH <http://www.pitt.edu/obc/ide/article-instances> {
        <##GRANTS##> dc:title ?title .
        <##GRANTS##> rdf:type ?types .
        <##GRANTS##> <http://purl.obolibrary.org/obo/ERO_0000480> ?linkout .
        <##GRANTS##> obo:IDE_0000000169 ?start  .
        <##GRANTS##> obo:IDE_0000000170 ?end .
        <##GRANTS##> obo:IDE_0000000171 ?pi .
        <##GRANTS##> obo:IDE_0000000173 ?agency .
        <##GRANTS##> obo:IDE_0000000172 ?foa .
        <##GRANTS##> obo:IDE_0000000174 ?awardee .
        <##GRANTS##> <http://purl.obolibrary.org/obo/APOLLO_SV_00000325> ?dateIndexed .
        <##GRANTID##> obo:IAO_0000219 <##GRANTS##> .
        <##GRANTID##> rdfs:label ?grantidlabel
    }
}
INSERT {
    GRAPH <http://www.pitt.edu/obc/ide/article-instances> { 
        <##GRANTS##> dc:title "##TITLE##" .
        <##GRANTS##> rdf:type  <##TYPE##> .
        <##GRANTS##> <http://purl.obolibrary.org/obo/ERO_0000480> "##LINKOUT##" .
        <##GRANTS##> obo:IDE_0000000171 "##PI##" .
        <##GRANTS##> obo:IDE_0000000174 "##AWARDEE##" .
        <##GRANTS##> obo:IDE_0000000172 "##FOA##" .
        <##GRANTS##> obo:IDE_0000000173 "##AGENCY##" .
        <##GRANTS##> obo:IDE_0000000169 "##START##"  .
        <##GRANTS##> obo:IDE_0000000170 "##END##" .
        <##GRANTID##> obo:IAO_0000219 <##GRANTS##> .
        <##GRANTID##> rdfs:label "##GRANTIDLABEL##" .
        <##GRANTS##> <http://purl.obolibrary.org/obo/APOLLO_SV_00000325> "##DATEINDEXED##" .
        ##ABOUTS##
    }
}


USING <http://www.pitt.edu/obc/ide/apollo-sv>
USING <http://www.pitt.edu/obc/ide/classes-and-indexing-instances>
USING <http://www.pitt.edu/obc/ide/article-instances>

WHERE {
    OPTIONAL { <##GRANTS##> dc:title ?title } .
    OPTIONAL { <##GRANTS##> rdf:type ?types } .
    OPTIONAL { <##GRANTS##> <http://purl.obolibrary.org/obo/ERO_0000480> ?linkout } .
    OPTIONAL { <##GRANTS##> obo:IDE_0000000171 ?pi } .
    OPTIONAL { <##GRANTS##> obo:IDE_0000000174 ?awardee } .
    OPTIONAL { <##GRANTS##> obo:IDE_0000000172 ?foa } .
    OPTIONAL { <##GRANTS##> obo:IDE_0000000173 ?agency } .
    OPTIONAL { <##GRANTS##> obo:IDE_0000000169 ?start } .
    OPTIONAL { <##GRANTS##> obo:IDE_0000000170 ?end } .
    OPTIONAL { <##GRANTID##> obo:IAO_0000219 <##GRANTS##> } .
    OPTIONAL { <##GRANTID##> rdfs:label ?grantidlabel } .
    OPTIONAL { <##GRANTS##> <http://purl.obolibrary.org/obo/APOLLO_SV_00000325> ?dateIndexed } .
}