
PREFIX geo: <http://purl.obolibrary.org/obo/geo.owl#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX ro: <http://www.obofoundry.org/ro/ro.owl#>
PREFIX obo: <http://purl.obolibrary.org/obo/>
PREFIX dc: <http://purl.org/dc/elements/1.1/>

SELECT DISTINCT ?title ?awardee ?foa ?agency ?pi ?grantidlabel ?start ?end ?pub ?linkout ?date ?sourceOrganization ?authors ?journal
    (group_concat(DISTINCT ?aboutLabel ; separator = " :: ") as ?abouts)
FROM <http://www.pitt.edu/obc/ide/apollo-sv>
FROM <http://www.pitt.edu/obc/ide/classes-and-indexing-instances>
FROM <http://www.pitt.edu/obc/ide/article-instances>
WHERE {
  
    ?grant rdf:type obo:OBI_0001636 .
    ?grant dc:title ?title .
    ?grant obo:IDE_0000000174 ?awardee .
    ?grant obo:IDE_0000000172 ?foa .
    ?grant obo:IDE_0000000173 ?agency .
    ?grant obo:IDE_0000000171 ?pi .
    ?grant obo:IDE_0000000169 ?start .
    ?grant obo:IDE_0000000170 ?end . 
    ?grantid obo:IAO_0000219 ?grant .
    ?grantid rdfs:label ?grantidlabel .
    ?grant obo:BFO_0000051 ?os . 
    ?os ^obo:OBI_0000417 ?pp .
    OPTIONAL { ?pp ^obo:IAO_0000136 ?pub } .  
    OPTIONAL { ?pub dc:title ?title } .
    OPTIONAL { ?pub <http://purl.obolibrary.org/obo/ERO_0000480> ?linkout } .
    OPTIONAL { ?pub <http://purl.org/dc/elements/1.1/date> ?date } .
    OPTIONAL { ?pub <http://www.pitt.edu/obc/IDE_source_organization> ?sourceOrganization } .
    OPTIONAL { ?pub <http://www.pitt.edu/obc/AUTHORS_1> ?authors } .
    OPTIONAL {
        ?pub <http://purl.obolibrary.org/obo/BFO_0000137> ?journalUri .
        ?journalUri dc:title ?journal .
    } .
    
    #used for string interpolation to filter based on search terms
    ##ABOUT##
    
} GROUP BY ?title ?awardee ?foa ?agency ?pi ?grantidlabel ?start ?end ?pub ?linkout ?date ?sourceOrganization ?authors ?journal
