PREFIX geo: <http://purl.obolibrary.org/obo/geo.owl#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX ro: <http://www.obofoundry.org/ro/ro.owl#>
PREFIX obo: <http://purl.obolibrary.org/obo/>
PREFIX dc: <http://purl.org/dc/elements/1.1/>


SELECT DISTINCT ?about ?aboutLabel
FROM <http://www.pitt.edu/obc/ide/apollo-sv>
FROM <http://www.pitt.edu/obc/ide/classes-and-indexing-instances>
FROM <http://www.pitt.edu/obc/ide/article-instances>
WHERE {
    <##ARTIFACT##> obo:IAO_0000136 ?about .
    ?about rdfs:label ?aboutLabel .
} 