PREFIX geo: <http://purl.obolibrary.org/obo/geo.owl#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX ro: <http://www.obofoundry.org/ro/ro.owl#>
PREFIX obo: <http://purl.obolibrary.org/obo/>
PREFIX dc: <http://purl.org/dc/elements/1.1/>

INSERT DATA {
    GRAPH <http://www.pitt.edu/obc/ide/article-instances> { 
        <##PUBLICATION##> dc:title "##TITLE##" .
        <##PUBLICATION##> <http://purl.obolibrary.org/obo/ERO_0000480> "##LINKOUT##" .
        <##PUBLICATION##> <http://www.pitt.edu/obc/AUTHORS_1> "##AUTHORS##" .
        <##PUBLICATION##> <http://purl.org/dc/elements/1.1/date> "##DATE##" . 
        <##PUBLICATION##> rdf:type <##TYPE##> .
        <##PUBLICATION##> <http://purl.obolibrary.org/obo/OBI_0001617> "##PMID##" .
        <##PUBLICATION##> <http://purl.obolibrary.org/obo/BFO_0000137> ?newJournal .
        <##PUBLICATION##> <http://www.pitt.edu/obc/IDE_0000000040> "##DOI##" .
        <##PUBLICATION##> <http://purl.obolibrary.org/obo/APOLLO_SV_00000325> "##DATEINDEXED##" .
        <##GRANT##> obo:BFO_0000051 <##OS##> .
        <##OS##> rdf:type obo:IAO_0000005 .
        <##PP##> obo:OBI_0000417 <##OS##> .
        <##PP##> rdf:type obo:IAO_0000011 .
        <##PUBLICATION##> obo:IAO_0000136 <##PP##> .
        ##ABOUTS##
    } 
} 
USING <http://www.pitt.edu/obc/ide/apollo-sv>
USING <http://www.pitt.edu/obc/ide/classes-and-indexing-instances>
USING <http://www.pitt.edu/obc/ide/article-instances>

WHERE {
        
    OPTIONAL { 
        ?newJournal rdf:type obo:FBcv_0000787 .
        {
            ?newJournal dc:title "##JOURNAL##"^^<http://www.w3.org/2001/XMLSchema#string> 
        } UNION {
            ?newJournal dc:title "##JOURNAL##"
        }    
    } .

}