
PREFIX geo: <http://purl.obolibrary.org/obo/geo.owl#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX ro: <http://www.obofoundry.org/ro/ro.owl#>
PREFIX obo: <http://purl.obolibrary.org/obo/>
PREFIX dc: <http://purl.org/dc/elements/1.1/>


DELETE {
    GRAPH <http://www.pitt.edu/obc/ide/article-instances> {
        <##PUBLICATION##> dc:title ?title .
        <##PUBLICATION##> <http://purl.obolibrary.org/obo/ERO_0000480> ?linkout .
        <##PUBLICATION##> <http://www.pitt.edu/obc/AUTHORS_1> ?authors .
        <##PUBLICATION##> <http://purl.org/dc/elements/1.1/date> ?date . 
        <##PUBLICATION##> obo:IAO_0000136 ?about .
        <##PUBLICATION##> rdf:type ?types .
        <##PUBLICATION##> <http://purl.obolibrary.org/obo/OBI_0001617> ?pmid .
        <##PUBLICATION##> <http://purl.obolibrary.org/obo/BFO_0000137> ?oldJournal .
        <##PUBLICATION##> <http://www.pitt.edu/obc/IDE_0000000040> ?doi .
        <##PUBLICATION##> <http://purl.obolibrary.org/obo/APOLLO_SV_00000325> ?dateIndexed .
    }
} INSERT {
    GRAPH <http://www.pitt.edu/obc/ide/article-instances> { 
        <##PUBLICATION##> dc:title "##TITLE##" .
        <##PUBLICATION##> <http://purl.obolibrary.org/obo/ERO_0000480> "##LINKOUT##" .
        <##PUBLICATION##> <http://www.pitt.edu/obc/AUTHORS_1> "##AUTHORS##" .
        <##PUBLICATION##> <http://purl.org/dc/elements/1.1/date> "##DATE##" . 
        <##PUBLICATION##> rdf:type <##TYPE##> .
        <##PUBLICATION##> <http://purl.obolibrary.org/obo/OBI_0001617> "##PMID##" .
        <##PUBLICATION##> <http://purl.obolibrary.org/obo/BFO_0000137> ?newJournal .
        <##PUBLICATION##> <http://www.pitt.edu/obc/IDE_0000000040> "##DOI##" .
        <##PUBLICATION##> <http://purl.obolibrary.org/obo/APOLLO_SV_00000325> "##DATEINDEXED##" .
        ##ABOUTS##
    } 
} 
USING <http://www.pitt.edu/obc/ide/apollo-sv>
USING <http://www.pitt.edu/obc/ide/classes-and-indexing-instances>
USING <http://www.pitt.edu/obc/ide/article-instances>

WHERE {
    OPTIONAL { <##PUBLICATION##> dc:title ?title } .
    OPTIONAL { <##PUBLICATION##> <http://purl.obolibrary.org/obo/ERO_0000480> ?linkout } .
    OPTIONAL { <##PUBLICATION##> <http://www.pitt.edu/obc/AUTHORS_1> ?authors } .
    OPTIONAL { <##PUBLICATION##> <http://purl.org/dc/elements/1.1/date> ?date } . 
    OPTIONAL { <##PUBLICATION##> obo:IAO_0000136 ?about } .
    OPTIONAL { <##PUBLICATION##> rdf:type ?types } .
    OPTIONAL { <##PUBLICATION##> <http://purl.obolibrary.org/obo/OBI_0001617> ?pmid } .
    OPTIONAL { <##PUBLICATION##> <http://www.pitt.edu/obc/IDE_0000000040> ?doi } .
    OPTIONAL { <##PUBLICATION##> <http://purl.obolibrary.org/obo/APOLLO_SV_00000325> ?dateIndexed } .
        
    OPTIONAL { 
        ?oldJournal rdf:type obo:FBcv_0000787 .
        <##PUBLICATION##> <http://purl.obolibrary.org/obo/BFO_0000137> ?oldJournal 
    } .
        
    OPTIONAL { 
        ?newJournal rdf:type obo:FBcv_0000787 .
        {
            ?newJournal dc:title "##JOURNAL##"^^<http://www.w3.org/2001/XMLSchema#string> 
        } UNION {
            ?newJournal dc:title "##JOURNAL##"
        }    
    } .
}
